# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mango\PycharmProjects\FanTools2\tool\translator\designer\TranslatorPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1452, 844)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(-1, 38, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RoundListWidget = RoundListWidget(Form)
        self.RoundListWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RoundListWidget.setObjectName("RoundListWidget")
        item = QtWidgets.QListWidgetItem()
        self.RoundListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RoundListWidget.addItem(item)
        self.horizontalLayout_3.addWidget(self.RoundListWidget)
        self.StackedWidget = OpacityAniStackedWidget(Form)
        self.StackedWidget.setObjectName("StackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ScrollArea = ScrollArea(self.page)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1038, 696))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ScrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.ScrollLayout.setContentsMargins(0, 0, 15, 0)
        self.ScrollLayout.setObjectName("ScrollLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ScrollLayout.addItem(spacerItem)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.ScrollArea)
        self.SimpleCardWidget = SimpleCardWidget(self.page)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SimpleCardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StrongBodyLabel_CreateExampleProject = StrongBodyLabel(self.SimpleCardWidget)
        self.StrongBodyLabel_CreateExampleProject.setObjectName("StrongBodyLabel_CreateExampleProject")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_CreateExampleProject)
        self.BodyLabel_CreateExampleProject = BodyLabel(self.SimpleCardWidget)
        self.BodyLabel_CreateExampleProject.setWordWrap(True)
        self.BodyLabel_CreateExampleProject.setObjectName("BodyLabel_CreateExampleProject")
        self.horizontalLayout.addWidget(self.BodyLabel_CreateExampleProject)
        self.PushButton_CreateExampleProject = qfluentwidgets.PushButton(self.SimpleCardWidget)
        self.PushButton_CreateExampleProject.setObjectName("PushButton_CreateExampleProject")
        self.horizontalLayout.addWidget(self.PushButton_CreateExampleProject)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.SimpleCardWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ToolButton_ImportNewProject = qfluentwidgets.ToolButton(self.page)
        self.ToolButton_ImportNewProject.setObjectName("ToolButton_ImportNewProject")
        self.verticalLayout_2.addWidget(self.ToolButton_ImportNewProject)
        self.ToolButton_AddExistedProject = qfluentwidgets.ToolButton(self.page)
        self.ToolButton_AddExistedProject.setObjectName("ToolButton_AddExistedProject")
        self.verticalLayout_2.addWidget(self.ToolButton_AddExistedProject)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.StackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.StackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.StackedWidget)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)

        self.retranslateUi(Form)
        self.StackedWidget.setCurrentIndex(0)
        self.RoundListWidget.currentRowChanged['int'].connect(self.StackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Translator"))
        __sortingEnabled = self.RoundListWidget.isSortingEnabled()
        self.RoundListWidget.setSortingEnabled(False)
        item = self.RoundListWidget.item(0)
        item.setText(_translate("Form", "Projects List"))
        item = self.RoundListWidget.item(1)
        item.setText(_translate("Form", "About Translator"))
        self.RoundListWidget.setSortingEnabled(__sortingEnabled)
        self.StrongBodyLabel_CreateExampleProject.setText(_translate("Form", "Example Project"))
        self.BodyLabel_CreateExampleProject.setText(_translate("Form", "We provide a example project from a PHP project for you to take a try!"))
        self.PushButton_CreateExampleProject.setText(_translate("Form", "Create Example Project"))
from qfluentwidgets import BodyLabel, OpacityAniStackedWidget, ScrollArea, SimpleCardWidget, StrongBodyLabel
from qfluentwidgetspro import RoundListWidget
