# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mango\PycharmProjects\FanTools2\app\view\designer\main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(929, 657)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SmoothScrollArea = SmoothScrollArea(Form)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 901, 629))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CardWidget = CardWidget(self.scrollAreaWidgetContents)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AvatarWidget = AvatarWidget(self.CardWidget)
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.horizontalLayout.addWidget(self.AvatarWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TitleLabel = TitleLabel(self.CardWidget)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.ToolButton_EditAccount = qfluentwidgets.ToolButton(self.CardWidget)
        self.ToolButton_EditAccount.setObjectName("ToolButton_EditAccount")
        self.gridLayout.addWidget(self.ToolButton_EditAccount, 0, 1, 1, 1)
        self.LargeTitleLabel_AccountName = LargeTitleLabel(self.CardWidget)
        self.LargeTitleLabel_AccountName.setObjectName("LargeTitleLabel_AccountName")
        self.gridLayout.addWidget(self.LargeTitleLabel_AccountName, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.CardWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SimpleCardWidget = SimpleCardWidget(self.scrollAreaWidgetContents)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SimpleCardWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel_SoftwareInfo = BodyLabel(self.SimpleCardWidget)
        self.BodyLabel_SoftwareInfo.setObjectName("BodyLabel_SoftwareInfo")
        self.horizontalLayout_4.addWidget(self.BodyLabel_SoftwareInfo)
        self.verticalLayout_2.addWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_2 = SimpleCardWidget(self.scrollAreaWidgetContents)
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SimpleCardWidget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel_AccountInfo = BodyLabel(self.SimpleCardWidget_2)
        self.BodyLabel_AccountInfo.setObjectName("BodyLabel_AccountInfo")
        self.horizontalLayout_3.addWidget(self.BodyLabel_AccountInfo)
        self.verticalLayout_2.addWidget(self.SimpleCardWidget_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.HeaderCardWidget = HeaderCardWidget(self.scrollAreaWidgetContents)
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.verticalLayout_3.addWidget(self.HeaderCardWidget)
        self.ElevatedCardWidget_YiYan = ElevatedCardWidget(self.scrollAreaWidgetContents)
        self.ElevatedCardWidget_YiYan.setObjectName("ElevatedCardWidget_YiYan")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ElevatedCardWidget_YiYan)
        self.verticalLayout_5.setContentsMargins(32, -1, 32, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.BodyLabel_YiYan = BodyLabel(self.ElevatedCardWidget_YiYan)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Normal)
        self.BodyLabel_YiYan.setFont(font)
        self.BodyLabel_YiYan.setObjectName("BodyLabel_YiYan")
        self.verticalLayout_5.addWidget(self.BodyLabel_YiYan)
        self.StrongBodyLabel_YiYan = StrongBodyLabel(self.ElevatedCardWidget_YiYan)
        self.StrongBodyLabel_YiYan.setObjectName("StrongBodyLabel_YiYan")
        self.verticalLayout_5.addWidget(self.StrongBodyLabel_YiYan, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.ElevatedCardWidget_YiYan)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.SmoothScrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "Welcome,"))
        self.LargeTitleLabel_AccountName.setText(_translate("Form", "Little Green Mango?"))
        self.BodyLabel_SoftwareInfo.setText(_translate("Form", "Body label"))
        self.BodyLabel_AccountInfo.setText(_translate("Form", "Body label"))
        self.BodyLabel_YiYan.setText(_translate("Form", "Body label"))
        self.StrongBodyLabel_YiYan.setText(_translate("Form", "Strong body label"))
from qfluentwidgets import AvatarWidget, BodyLabel, CardWidget, ElevatedCardWidget, HeaderCardWidget, LargeTitleLabel, SimpleCardWidget, SmoothScrollArea, StrongBodyLabel, TitleLabel
