site_name: 芒果工具箱文档中心
site_description: 芒果工具箱的帮助文档！
site_author: 芒果帆帆w
repo_url: https://github.com/mangofanfan/FanTools2
site_url: https://docs-fantools.mangofanfan.cn/

nav:
  - 主页: index.md
  - 开始使用: start_use.md
  - 运行日志: log.md
  - 版本记录: version.md
  - 贡献代码: contribute.md

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - search.highlight        # 搜索高亮
    - search.share           # 搜索分享
    - search.suggest         # 搜索建议
  language: zh
  palette:
    - search:
        placeholder: 搜索文档
        result:
          no_results_text: 未找到相关结果
          searching_text: 正在搜索...
    # 配置切换按钮
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式
      primary: indigo
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  - search:
      # 搜索索引设置
      lang:
        - en
        - zh
      separator: '[\s\-\.]+'    # 分词分隔符

extra_javascript:
  - javascripts/theme-switch.js