site_name: 芒果工具箱文档中心
site_description: 芒果工具箱的帮助文档！
site_author: 芒果帆帆w
repo_url: https://github.com/mangofanfan/FanTools2
site_url: https://docs-fantools.mangofanfan.cn/
nav:
  - 主页: index.md
  - 开始使用: start_use.md
  - 运行日志: log.md
  - 版本记录: version.md
  - 贡献代码: contribute.md
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true