# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mango\PycharmProjects\FanTools2\app\tool\hashCalculator\designer\hash_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 682)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(12, 45, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SimpleCardWidget = SimpleCardWidget(Form)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SimpleCardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconWidget = IconWidget(self.SimpleCardWidget)
        self.IconWidget.setMinimumSize(QtCore.QSize(24, 24))
        self.IconWidget.setMaximumSize(QtCore.QSize(24, 24))
        self.IconWidget.setObjectName("IconWidget")
        self.horizontalLayout.addWidget(self.IconWidget)
        self.BodyLabel = BodyLabel(self.SimpleCardWidget)
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.verticalLayout_2.addWidget(self.SimpleCardWidget)
        self.DropMultiFilesWidget = DropMultiFilesWidget(Form)
        self.DropMultiFilesWidget.setObjectName("DropMultiFilesWidget")
        self.verticalLayout_2.addWidget(self.DropMultiFilesWidget)
        self.SmoothScrollArea = SmoothScrollArea(Form)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1066, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.SmoothScrollArea)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from qfluentwidgets import BodyLabel, IconWidget, SimpleCardWidget, SmoothScrollArea
from qfluentwidgetspro import DropMultiFilesWidget
