# 这里是有关窗口化启动的配置文件……
import os


class config:
    version_tag = "当前版本：1.0.0-last"
    window_name = "古典英语 密码解释器"
    icon_path = os.path.dirname(__file__)+"/SimpleCrypt/SimpleCrypt.ico"
    background_path = os.path.dirname(__file__)+"/SimpleCrypt/BackGround.png"
    lang_main_title = "古典英语 密码解释器\nSimpleCrypt"
    lang_main_author = "制作：芒果帆帆w"
    lang_notice = "本程序开源于码云Gitee，不需遵守任何协议"
    lang_confirm_1 = "确认加密"
    lang_confirm_2 = "确认解密"
    messagebox_title = "解释结果"
    working_region_title = "工作区"
    lang_output_1_1 = "本次加密的输出结果为："
    lang_output_1_2 = "解密的原文："
    lang_output_3 = "使用的秘钥："
    lang_output_4 = "您可以从日志窗口复制结果……"
    lang_output_2_1 = "本次解密的输出结果为："
    lang_output_2_2 = "加密的原文："
    lang_still_not_1 = "（您仍未进行过加密……这里空荡荡的欸）"
    lang_still_not_2 = "（您仍未进行过解密……这里空荡荡的欸）"
    lang_info = "[INFO]"
    lang_log_0 = "|||"
    lang_log_1 = "这里会显示启动后的解释日志……\n当然您也可以对其进行手动编辑……？\n\n"
    lang_wait_for_input = "（请在此输入一串英语字母，不能有空格、数字、字符等）"
    lang_wait_for_key_1 = "（请在此输入秘钥，仅支持输入一个数字）"
    lang_wait_for_key_2 = "（请在此输入秘钥，仅支持输入一串英语字母，要求同上）"
    lang_clean_all = "清空所有输入内容"
    lang_tip_label = "点击此处查看解释器的工作说明"
    url_help_web = "https://www.fancraft.top/index.php/archives/166"
    lang_hello_label = "欢迎使用！"
    warning_title = "警告"
    warning_no_key = "请输入一个确切的秘钥！"
    warning_not_int_key = "请输入一个整数作为秘钥！"
    warning_not_str_key = "请输入一个纯字母字符串作为秘钥！"
    warning_not_str_input = "请输入一个纯字母字符串作为输入值！"
    warning_no_input = "请输入一个确切的字符串作为输入！"
    lang_save_log_to_txt = "将日志保存到本地文本……"

    logger_title = "日志写入窗口 - 写入完毕记得关闭"
    logger_input_written_txt_name_1 = "需要写入的日志文件名称"
    logger_input_written_txt_name_2 = "log"
    lang_wait_for_logging_text = "需要写入日志的内容预览"
    lang_confirm_logging_bottom = "确认将以下内容写入日志"
    log_success = "写入日志成功"
    log_failed = "写入日志失败"
